export const languages = [
  { id: "javascript", name: "JavaScript", executable: true },
  { id: "typescript", name: "TypeScript", executable: true },
  { id: "python", name: "Python", executable: true },
  { id: "java", name: "Java", executable: false },
  { id: "cpp", name: "C++", executable: false },
  { id: "c", name: "C", executable: false },
  { id: "csharp", name: "C#", executable: false },
  { id: "php", name: "PHP", executable: false },
  { id: "ruby", name: "Ruby", executable: false },
  { id: "go", name: "Go", executable: false },
  { id: "rust", name: "Rust", executable: false },
  { id: "swift", name: "Swift", executable: false },
  { id: "kotlin", name: "Kotlin", executable: false },
  { id: "scala", name: "Scala", executable: false },
  { id: "html", name: "HTML", executable: true },
  { id: "css", name: "CSS", executable: true },
  { id: "json", name: "JSON", executable: true },
  { id: "xml", name: "XML", executable: true },
  { id: "yaml", name: "YAML", executable: true },
  { id: "sql", name: "SQL", executable: false },
  { id: "markdown", name: "Markdown", executable: true },
  { id: "shell", name: "Shell/Bash", executable: false },
  { id: "powershell", name: "PowerShell", executable: false },
];
